teacher: 
  max_difficulty: 50
  difficulty_grouper: steps
  difficulty_resolution: 10
  type: babysteps
  interval_policy: linear
  interval_parameter: [150, 600]
  increment_policy: fixed
  increment_parameter: 1
  old_task_quota: 0.2