teacher: 
  max_difficulty: 40
  difficulty_grouper: steps
  difficulty_resolution: 10
  type: babysteps
  interval_policy: fixed
  interval_parameter: 150
  increment_policy: fixed
  increment_parameter: 1
  old_task_quota: 0.2